### ISSUE TITLE
Update references and browser

### ISSUE THREAD

**Issue by aersida** [vitogit/tdd-mocha-chai-riot#3]
I found this extremely useful in setting up testing for the Cordova / Riot project I'm working on.
But I did need to update all of the references and swap out phantomJS for ChromeHeadless.
I have a commit ready with the updates if you want it.

**Comment by vitogit** [comment]
That's really good to hear. 
Yes you can create a PR, that would be great. Thanks

**Comment by aersida** [comment]
Can you give me permission to do that (add a new branch)

**Comment by vitogit** [comment]
I think you don't need permission. The process is like this: you have to fork the project, clone the fork, create new branch, make the changes, push to your fork and then create the PR against this project master branch. I know is kind of tedious 😞 

Example https://github.com/vitogit/tdd-mocha-chai-riot/pull/2

**Comment by aersida** [comment]
done

**Comment by vitogit** [comment]
Thanks, really appreciate it
Closing this issue because the PR was merged: https://github.com/vitogit/tdd-mocha-chai-riot/pull/4
